application:
  title: Have Your Dessert
user:
  edit:
    idiom: edit my profile
    cannonical: edit your profile  
post:
  edit:
    idiom:  edit my post
    cannonical: edit your post
  show:    
    idiom: "Post that I just clicked on"
    cannonical: "Show Post"

